#!/usr/bin/env python3
"""
SIH26025 TinyML C Header Exporter
Converts trained statistical and threshold parameters into C/C++ header constants.
"""

import json
import os
import sys

def export_c_header(params_path=None, output_header_path=None):
    base_dir = os.path.dirname(__file__)
    if not params_path:
        params_path = os.path.join(base_dir, "trained_params.json")
    if not output_header_path:
        output_header_path = os.path.join(base_dir, "..", "firmware", "include", "tinyml_weights.h")

    if not os.path.exists(params_path):
        from train_anomaly_detector import train_detector
        params = train_detector()
    else:
        with open(params_path, "r", encoding="utf-8") as f:
            params = json.load(f)

    header_content = f"""/**
 * @file tinyml_weights.h
 * @brief Auto-generated TinyML baseline weights and thresholds for ESP32-S3
 * Generated by ml/tinyml_export.py from SIH26025 training pipeline
 */

#pragma once

// Trained Baseline Statistics
#define BASELINE_TILT_MEAN_DEG          {params['tilt_mean']:.4f}f
#define BASELINE_TILT_STD_DEG           {params['tilt_std']:.4f}f
#define BASELINE_TILT_MAD_DEG           {params['tilt_mad']:.4f}f

#define BASELINE_DISP_MEAN_MM           {params['disp_mean']:.4f}f
#define BASELINE_DISP_STD_MM            {params['disp_std']:.4f}f
#define BASELINE_DISP_MAD_MM            {params['disp_mad']:.4f}f

#define BASELINE_VIB_MEAN_RMS           {params['vib_mean']:.4f}f
#define BASELINE_VIB_STD_RMS            {params['vib_std']:.4f}f

#define BASELINE_STRAIN_MEAN_UE         {params['strain_mean']:.4f}f
#define BASELINE_STRAIN_STD_UE          {params['strain_std']:.4f}f

// Edge Decision Thresholds
#define EDGE_Z_SCORE_THRESHOLD          {params['z_threshold']:.2f}f
#define EDGE_TILT_RATE_THRESH_DEG_HR    {params['tilt_rate_threshold_deg_hr']:.2f}f
#define EDGE_DISP_RATE_THRESH_MM_HR     {params['disp_rate_threshold_mm_hr']:.2f}f
#define EDGE_VIB_THRESH_RMS             {params['vib_threshold_rms']:.2f}f

#define TRAINING_SAMPLES_COUNT          {params['samples_trained']}
"""

    os.makedirs(os.path.dirname(output_header_path), exist_ok=True)
    with open(output_header_path, "w", encoding="utf-8") as f:
        f.write(header_content)

    print(f"[OK] TinyML weights exported -> {output_header_path}")

if __name__ == "__main__":
    export_c_header()
