/**
 * @file tinyml_weights.h
 * @brief Auto-generated TinyML baseline weights and thresholds for ESP32-S3
 * Generated by ml/tinyml_export.py from SIH26025 training pipeline
 */

#pragma once

// Trained Baseline Statistics
#define BASELINE_TILT_MEAN_DEG          12.4227f
#define BASELINE_TILT_STD_DEG           0.2156f
#define BASELINE_TILT_MAD_DEG           0.1945f

#define BASELINE_DISP_MEAN_MM           18.4990f
#define BASELINE_DISP_STD_MM            0.0831f
#define BASELINE_DISP_MAD_MM            0.0600f

#define BASELINE_VIB_MEAN_RMS           1.7945f
#define BASELINE_VIB_STD_RMS            0.1513f

#define BASELINE_STRAIN_MEAN_UE         419.9648f
#define BASELINE_STRAIN_STD_UE          1.4747f

// Edge Decision Thresholds
#define EDGE_Z_SCORE_THRESHOLD          2.50f
#define EDGE_TILT_RATE_THRESH_DEG_HR    0.50f
#define EDGE_DISP_RATE_THRESH_MM_HR     2.00f
#define EDGE_VIB_THRESH_RMS             4.50f

#define TRAINING_SAMPLES_COUNT          650
