/**
 * SIH26025 Data Provenance & Integrity Classification
 * 
 * Safety & Scientific Truth Mandate:
 * Every data point, risk calculation, alert, and map feature must be
 * explicitly tagged with its source classification. Synthetic or simulated
 * data must never masquerade as real field data.
 */

export type DataProvenance =
  | 'LIVE'
  | 'SIMULATED'
  | 'DEMO'
  | 'HISTORICAL'
  | 'EXTERNAL'
  | 'EXPERIMENTAL'
  | 'ASSUMPTION';

export const DATA_PROVENANCES: readonly DataProvenance[] = [
  'LIVE',
  'SIMULATED',
  'DEMO',
  'HISTORICAL',
  'EXTERNAL',
  'EXPERIMENTAL',
  'ASSUMPTION',
] as const;

export interface ProvenanceBadgeConfig {
  provenance: DataProvenance;
  label: string;
  badgeClass: string;
  description: string;
}

export const PROVENANCE_CONFIGS: Record<DataProvenance, ProvenanceBadgeConfig> = {
  LIVE: {
    provenance: 'LIVE',
    label: 'LIVE SENSING',
    badgeClass: 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border-emerald-300 dark:border-emerald-800 font-mono text-[10px]',
    description: 'Direct ingestion from physical ESP32 edge telemetry node.',
  },
  SIMULATED: {
    provenance: 'SIMULATED',
    label: 'SIMULATED',
    badgeClass: 'bg-cyan-50 dark:bg-cyan-950/50 text-cyan-800 dark:text-cyan-300 border-cyan-300 dark:border-cyan-800 font-mono text-[10px]',
    description: 'Dynamic temporal data generated by active mine-event simulation session.',
  },
  DEMO: {
    provenance: 'DEMO',
    label: 'DEMO SYNTHETIC',
    badgeClass: 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border-slate-300 dark:border-slate-700 font-mono text-[10px]',
    description: 'Pre-calibrated benchmark dataset representing Jharia Coalfield geological conditions.',
  },
  HISTORICAL: {
    provenance: 'HISTORICAL',
    label: 'HISTORICAL ARCHIVE',
    badgeClass: 'bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400 border-slate-300 dark:border-slate-800 font-mono text-[10px]',
    description: 'Historical mine subsidence records from past DGMS case studies.',
  },
  EXTERNAL: {
    provenance: 'EXTERNAL',
    label: 'EXTERNAL InSAR',
    badgeClass: 'bg-purple-50 dark:bg-purple-950/50 text-purple-700 dark:text-purple-300 border-purple-300 dark:border-purple-800 font-mono text-[10px]',
    description: 'External satellite-derived observation layer (Sentinel-1 InSAR synthetic baseline).',
  },
  EXPERIMENTAL: {
    provenance: 'EXPERIMENTAL',
    label: 'EXPERIMENTAL',
    badgeClass: 'bg-amber-50 dark:bg-amber-950/50 text-amber-800 dark:text-amber-300 border-amber-300 dark:border-amber-800 font-mono text-[10px]',
    description: 'Experimental edge-AI model output undergoing calibration.',
  },
  ASSUMPTION: {
    provenance: 'ASSUMPTION',
    label: 'GEOTECH ASSUMPTION',
    badgeClass: 'bg-zinc-100 dark:bg-zinc-900 text-zinc-700 dark:text-zinc-300 border-zinc-300 dark:border-zinc-700 font-mono text-[10px]',
    description: 'Geotechnical empirical parameter (e.g. angle of draw, depth-to-subsidence ratio).',
  },
};

export function isValidProvenance(value: unknown): value is DataProvenance {
  return typeof value === 'string' && DATA_PROVENANCES.includes(value as DataProvenance);
}

export function getProvenanceConfig(provenance: DataProvenance): ProvenanceBadgeConfig {
  return PROVENANCE_CONFIGS[provenance] ?? PROVENANCE_CONFIGS.DEMO;
}
