/**
 * SIH26025 Data Provenance & Integrity Classification
 * 
 * Safety & Scientific Truth Mandate:
 * Every data point, risk calculation, alert, and map feature must be
 * explicitly tagged with its source classification. Synthetic or simulated
 * data must never masquerade as real field data.
 */

export type DataProvenance =
  | 'LIVE'
  | 'SIMULATED'
  | 'DEMO'
  | 'HISTORICAL'
  | 'EXTERNAL'
  | 'EXPERIMENTAL'
  | 'ASSUMPTION';

export const DATA_PROVENANCES: readonly DataProvenance[] = [
  'LIVE',
  'SIMULATED',
  'DEMO',
  'HISTORICAL',
  'EXTERNAL',
  'EXPERIMENTAL',
  'ASSUMPTION',
] as const;

export interface ProvenanceBadgeConfig {
  provenance: DataProvenance;
  label: string;
  badgeClass: string;
  description: string;
}

export const PROVENANCE_CONFIGS: Record<DataProvenance, ProvenanceBadgeConfig> = {
  LIVE: {
    provenance: 'LIVE',
    label: 'LIVE SENSING',
    badgeClass: 'bg-emerald-600 text-white font-mono text-[10px] tracking-wider',
    description: 'Direct ingestion from physical ESP32 edge telemetry node.',
  },
  SIMULATED: {
    provenance: 'SIMULATED',
    label: 'SIMULATED',
    badgeClass: 'bg-cyan-600 text-white font-mono text-[10px] tracking-wider',
    description: 'Dynamic temporal data generated by active mine-event simulation session.',
  },
  DEMO: {
    provenance: 'DEMO',
    label: 'DEMO SYNTHETIC',
    badgeClass: 'bg-indigo-600 text-white font-mono text-[10px] tracking-wider',
    description: 'Pre-calibrated benchmark dataset representing Jharia Coalfield geological conditions.',
  },
  HISTORICAL: {
    provenance: 'HISTORICAL',
    label: 'HISTORICAL ARCHIVE',
    badgeClass: 'bg-slate-600 text-white font-mono text-[10px] tracking-wider',
    description: 'Historical mine subsidence records from past DGMS case studies.',
  },
  EXTERNAL: {
    provenance: 'EXTERNAL',
    label: 'EXTERNAL InSAR',
    badgeClass: 'bg-purple-600 text-white font-mono text-[10px] tracking-wider',
    description: 'External satellite-derived observation layer (Sentinel-1 InSAR synthetic baseline).',
  },
  EXPERIMENTAL: {
    provenance: 'EXPERIMENTAL',
    label: 'EXPERIMENTAL',
    badgeClass: 'bg-amber-600 text-white font-mono text-[10px] tracking-wider',
    description: 'Experimental edge-AI model output undergoing calibration.',
  },
  ASSUMPTION: {
    provenance: 'ASSUMPTION',
    label: 'GEOTECH ASSUMPTION',
    badgeClass: 'bg-zinc-600 text-white font-mono text-[10px] tracking-wider',
    description: 'Geotechnical empirical parameter (e.g. angle of draw, depth-to-subsidence ratio).',
  },
};

export function isValidProvenance(value: unknown): value is DataProvenance {
  return typeof value === 'string' && DATA_PROVENANCES.includes(value as DataProvenance);
}

export function getProvenanceConfig(provenance: DataProvenance): ProvenanceBadgeConfig {
  return PROVENANCE_CONFIGS[provenance] ?? PROVENANCE_CONFIGS.DEMO;
}
